%YAML 1.2
---
run_duration:
  description: Simulation run time
  value:
    type: float
    default: 1.0
    units: s
    range:
      min: 0
      max: 1000000
---
thermal_diffusivity:
  name: Thermal diffusivity
  description: Thermal diffusivity
  value:
    type: float
    default: 1.0
    range:
      min: 0.0
      max: 10.0
    units: m^2/s
---
number_of_rows:
  name: Number of rows
  description: Number of grid rows.
  value:
    type: int
    default: 10
    range:
      min: 1
      max: 10000
    units: -

number_of_columns:
  name: Number of columns
  description: Number of grid columns.
  value:
    type: int
    default: 20
    range:
      min: 1
      max: 10000
    units: -

row_spacing:
  name: Row spacing
  description: Distance between grid rows.
  value:
    type: float
    default: 1.0
    range:
      min: 0.1
      max: 10000
    units: m

column_spacing:
  name: Column spacing
  description: Distance between grid columns.
  value:
    type: float
    default: 1.0
    range:
      min: 0.1
      max: 10000
    units: m

grid_origin_x:
  name: X-coordinate of grid origin
  description: The x-coordinate of the lower-left corner of the grid.
  value:
    type: float
    default: 0.0
    range:
      min: -10000
      max: 10000
    units: -

grid_origin_y:
  name: Y-coordinate of grid origin
  description: The y-coordinate of the lower-left corner of the grid.
  value:
    type: float
    default: 0.0
    range:
      min: -10000
      max: 10000
    units: -
